Repository qlik-oss/k-apis, pull requests merged in 2020-02, with the labels that each got.

#14 adding git operations and repo restructure
  git/git.go
  git/git_test.go
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/type.go
  pkg/cr/cr-main.go
  pkg/git/git.go
  pkg/git/git_test.go
  pkg/keys/generator.go
  pkg/keys/generator_test.go
  pkg/qust/patch_configs.go
  pkg/qust/patch_configs_test.go
  pkg/qust/patch_keys.go
  pkg/qust/patch_keys_test.go
  pkg/qust/patch_namespace.go
  pkg/qust/patch_namespace_test.go
  pkg/qust/patch_secrets.go
  pkg/qust/patch_secrets_test.go
  pkg/qust/patch_storage_class.go
  pkg/qust/patch_storage_class_test.go
  pkg/qust/patch_utils.go
  pkg/qust/patch_utils_test.go
  pkg/state/backup_restore.go
  pkg/state/backup_restore_test.go
Labels: kind/enhancement

#18 fix AddConfigs and AddSecrets method
  .gitignore
  pkg/config/config.go
  pkg/config/config_test.go
Labels: kind/enhancement, size/S

#19 add label patch to change release name
  README.md
  pkg/config/type.go
  pkg/cr/cr-main.go
  pkg/qust/patch_configs.go
  pkg/qust/patch_release_name.go
  pkg/qust/patch_release_name_test.go
  pkg/qust/patch_secrets.go
  pkg/qust/patch_storage_class_test.go
  pkg/qust/patch_utils.go
  pkg/qust/patch_utils_test.go
Labels: kind/enhancement, size/S

#21 change name
  pkg/cr/cr-main.go
  pkg/qust/patch_release_name.go
Labels: bug
